### ISSUE TITLE
oauthToken is set to itself instead of the one in a higher scope with the same name

### ISSUE THREAD

**Issue by macdja38** [ChangeJar/payments-demo#1]
https://github.com/ChangeJar/payments-demo/blob/master/changejar_api/oauthFetch.js#L40

**Comment by RobNielsen515** [comment]
Yep. Good catch. Fixed in https://github.com/ChangeJar/payments-demo/commit/7a9b612fe17fcdc700fc1a9c21e5228ca3dc1c50
